PR - add missing values for snow profile
NVE/varsom-observation pull request #84
Opened 2023-08-01 10:24 UTC by joergenlampe

Added temperature and exposition info 
Some css adjustments
Some bug fixes

2023-08-16 09:13 UTC, gruble requested changes
Se kommentarer.
Kan du også legge inn en ID til en observasjon i PR'en som inneholder tetthetsmålinger, så vi får testet at disse vises riktig?

2023-08-16 17:13 UTC, joergenlampe commented on src/components/varsom-snow-profile2/varsom-snow-profile2.tsx
> +{/**
Jeg hadde en kommentar til det. Se her: 
https://nveprojects.atlassian.net/browse/RO-2407

2023-08-17 08:42 UTC, gruble commented on src/components/varsom-snow-density-layer/varsom-snow-density-layer.tsx
> +    _key={this.strings && !this.shortVersion ? this.strings.Observations.SnowProfile.Density.WaterEquivalent : (this.shortVersion ? null : "Vannekv. (mm)") }
Høres lovende ut!

2023-08-17 08:45 UTC, gruble commented on src/components/varsom-snow-profile2/varsom-snow-profile2.tsx
> +{/**
Aha! Ser ikke ut som du har fått svar på den. Men siden den er på beta, tenker jeg du kan ta den med. Da får jeg heller ta skylda om noen ikke ønsker å se det.

2023-08-22 11:15 UTC, joergenlampe commented on src/components/varsom-snow-profile2/varsom-snow-profile2.tsx
> +{/**
Har lagt det til nå. Sjekk regid: 350867. Hvis det skal være komma mellom lagene, blir det et ekstra komma på slutten... kan vi bruke punktum i stedet? Hvis ikke må jeg sende med en counter til SnowDensityLayer-komponenten og bare vise komma hvis ikke det er siste lag.... eller finnes det en enklere løsning?

2023-08-22 12:43 UTC, gruble commented on src/components/varsom-snow-profile2/varsom-snow-profile2.tsx
> +{/**
Siden SnowDensityLayer ikke vet om de andre lagene og heller ikke bør vite om den, så tror jeg visningen av komma bør flyttes til komponenten over.
Komma er nok det beste. Forholdsvis enkelt å løse hvis det hadde vært en ren Javascript-løsning med join(), men måtte Google litt for å finne en løsning i HTML/CSS. Kanskje dette kan funke?
https://markheath.net/post/css-comma-separated-list

2023-08-22 12:54 UTC, gruble requested changes
Får du komma mellom målingene i temperaturprofilen og fjernet komma etter siste tetthetsmåling, er vi i mål:)

2023-08-22 13:52 UTC, joergenlampe commented on src/components/varsom-snow-profile2/varsom-snow-profile2.tsx
> +{/**
Fiksa nå. Tenkte ikke på CSS her. Det var jo genialt. Takk :)

2023-08-23 07:26 UTC, gruble approved these changes
Lekkert!

2023-08-23 10:29 UTC, merged