PR - created component for avalanche icons (valid exposition and exposed height)
NVE/varsom-observation pull request #97
Opened 2023-08-17 11:24 UTC by joergenlampe

2023-08-17 12:45 UTC, gruble requested changes
Det var kjapt levert!
Fin løsning og bra med gjenbruk.
Har bare noen spørsmål / kommentarer.

2023-08-18 06:54 UTC, joergenlampe commented on src/components/varsom-exposed-height/varsom-exposed-height.tsx
> +    @Prop() ValidExposition: any;
Det ble satt any slik at man skulle kunne sende inn null som prop hvis verdi ikke er satt. Jeg var ikke klar over at det var noen ulempe med det.

2023-08-18 08:24 UTC, gruble commented on src/components/varsom-exposed-height/varsom-exposed-height.tsx
> +    @Prop() ValidExposition: any;
Jeg skjønner at det er kjekt å kunne la en property kunne være null eller undefined.
Ulempen er at man da kan sende inn hva som helst. Da er det lov å skrive ValidExposition = 'helt feil', f.eks.
Det du kunne gjort hvis du vil ha sterk typing og null-støtte er dette:
`@Prop() ValidExposition: number | undefined;`
eller
`@Prop() ValidExposition: number | null;`

2023-08-18 08:29 UTC, gruble commented on src/components/varsom-exposed-height/varsom-exposed-height.tsx
> +    @Prop() ValidExposition: any;
Står litt om det her:
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html

2023-08-18 09:12 UTC, joergenlampe commented on src/components/varsom-exposed-height/varsom-exposed-height.tsx
> +<span class="avalanche-height-container">
Jeg så gjennom veldig mange observasjoner i APIet og fant ingen tilfeller av dette, så jeg tenkte at det ikke var mulig å registrere. Jeg har ikke lagt inn logikk for det, så hvis det skulle skje vil det ikke vises noe. Men jeg kan selvfølgelig legge inn logikk for det om nødvendig.

2023-08-18 09:14 UTC, joergenlampe commented on src/components/varsom-exposed-height/varsom-exposed-height.tsx
> +    @Prop() ValidExposition: any;
Skjønner. Er nok lurt å endre dette. Laget en egen oppgave på det.

2023-08-18 10:16 UTC, gruble commented on src/components/varsom-exposed-height/varsom-exposed-height.tsx
> +<span class="avalanche-height-container">
Ok, vi trenger ikke gjøre det nå. Lag en oppgave på det du, så blir det ikke glemt.

2023-08-18 10:34 UTC, joergenlampe commented on src/components/varsom-exposed-height/readme.md
> +# varsom-water-level2
fiksa det. Trodde hele filen ble autogenerert, men ikke headeren tydeligvis...

2023-08-21 09:21 UTC, gruble approved these changes

2023-08-21 13:44 UTC, merged